_ipsum_doctrine_orm:
    pattern:  /doctrine-orm
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:index }

_ipsum_doctrine_orm_create:
    pattern:  /doctrine-orm/create
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:create }

_ipsum_doctrine_orm_customrepository:
    pattern:  /doctrine-orm/custom-repository
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:customRepository }

_ipsum_doctrine_orm_delete:
    pattern:  /doctrine-orm/delete/{id}
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:delete }
    requirements:
        id: ^\d+$
