knp_ipsum_gedmo_extensions:
    pattern:  /gedmo-extensions
    defaults: { _controller: KnpIpsumBundle:GedmoExtensions:index }

knp_ipsum_gedmo_extensions_create:
    pattern:  /gedmo-extensions/create
    defaults: { _controller: KnpIpsumBundle:GedmoExtensions:create }

knp_ipsum_gedmo_extensions_update:
    pattern:  /gedmo-extensions/update/{id}
    defaults: { _controller: KnpIpsumBundle:GedmoExtensions:update }
    requirements:
        id: ^\d+$
