_ipsum_login:
    pattern:  /secured/login
    defaults: { _controller: KnpIpsumBundle:Secured:login }
    
_security_check:
    pattern:  /secured/login_check
    defaults: { _controller: KnpIpsumBundle:Secured:securityCheck }
    
_ipsum_logout:
    pattern:  /secured/logout
    defaults: { _controller: KnpIpsumBundle:Secured:logout }
    
_ipsum_secured:
    pattern:  /secured
    defaults: { _controller: KnpIpsumBundle:Secured:index }

_ipsum_secured_admin:
    pattern:  /secured/admin
    defaults: { _controller: KnpIpsumBundle:Secured:admin }
