_ipsum_swiftmailer:
    pattern:  /swiftmailer
    defaults: { _controller: KnpIpsumBundle:Swiftmailer:index }

_ipsum_swiftmailer_send:
    pattern:  /swiftmailer/send
    defaults: { _controller: KnpIpsumBundle:Swiftmailer:send }
