_imagine:
    resource: .
    type:     imagine

_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin

knp_ipsum:
    resource: "@KnpIpsumBundle/Resources/config/routing.yml"
