_imagine:
    resource: .
    type:     imagine

_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /ipsum/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /ipsum/admin

_ipsum:
    resource: "@KnpIpsumBundle/Resources/config/routing.yml"
